services:
  postgres:
    image: postgres:latest
    container_name: ecommerce_db_container
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    env_file:
      - backend/.env.dev